### ISSUE TITLE
Fail to select phenotype on Webservice 

### ISSUE THREAD

**Issue by MaryemT** [avalanche-org/Gen-Assoc#45]
[Archive.zip](https://github.com/avalanche-org/Gen-Assoc/files/10066110/Archive.zip)

I tried to use the GUI to analyze this data set. For some reason, the summary.R can see that there is a phenotype column but it is not detected once we have to select the phenotype from the dropdown list. You can test and see. 
 
✌🏾

**Comment by Jukoo** [comment]
We will fix this tomorrow at our weekly meeting.

**Comment by Jukoo** [comment]
The big problem is that some files do not respect the required format. So a small script has been created to solve this problem.  
not so perfect but it manages it  
```
restructure.py  filename 
```
